//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRSM.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activites()
        {
            this.Membre = new HashSet<Membres>();
        }
    
        public int Id { get; set; }
        public string MembreId { get; set; }
        public string Titre { get; set; }
        public string Jeu { get; set; }
        public string Description { get; set; }
        public int NbrMembreMin { get; set; }
        public int NbrMembreMax { get; set; }
        public int Jour { get; set; }
        public System.TimeSpan HeureDebut { get; set; }
        public bool Hebdomadaire { get; set; }
        public System.DateTime DateDebut { get; set; }
        public int NbrRepetition { get; set; }
        public bool Accepte { get; set; }
        public string Participant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membres> Membre { get; set; }
    }
}
