//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRSM.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CjrsmBDContainer : DbContext
    {
        public CjrsmBDContainer()
            : base("name=CjrsmBDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Membre> MembreSet { get; set; }
        public virtual DbSet<Jeux> JeuxSet { get; set; }
        public virtual DbSet<Livres> LivresSet { get; set; }
        public virtual DbSet<Activite> ActiviteSet { get; set; }
    }
}
