//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donnees.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CJRSMContainer : DbContext
    {
        public CJRSMContainer()
            : base("name=CJRSMContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
<<<<<<< HEAD:CJRSM/Donnees/Models/DAL/CJRSM.Context.cs
        public virtual DbSet<Membres> Membres { get; set; }
        public virtual DbSet<Jeux> Jeux { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Activites> Activites { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<Publications> Publications { get; set; }
=======
        public virtual DbSet<Membre> MembreSet { get; set; }
        public virtual DbSet<Jeux> JeuxSet { get; set; }
        public virtual DbSet<Documents> DocumentsSet { get; set; }
        public virtual DbSet<Activite> ActiviteSet { get; set; }
        public virtual DbSet<Publication> PublicationSet { get; set; }
>>>>>>> defb080538b62100585d77ff091871497249917d:CJRSM/Donnees/Models/DAL/CjrsmBD.Context.cs
    }
}
