//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRSM.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CJRSMContainer : DbContext
    {
        public CJRSMContainer()
            : base("name=CJRSMContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Membres> Membres { get; set; }
        public virtual DbSet<Jeux> Jeux { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Activites> Activites { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<Publications> Publications { get; set; }
    }
}
