//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donnees.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Auteur { get; set; }
        public string Disponible { get; set; }
        public string DateAjout { get; set; }
        public int MembreId { get; set; }
    
        public virtual Membre Membre { get; set; }
    }
}
