//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRSM.Models.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Jeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jeu()
        {
            this.ActiviteJeus = new HashSet<ActiviteJeu>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Titre")]
        public string Titre { get; set; }
        [Display(Name = "Difficulté")]
        public int Difficulte { get; set; }
        [Display(Name = "Nombre de joueur Minimal")]
        public int NbrJoueurMin { get; set; }
        [Display(Name = "Nombre de joueur Maximal")]
        public int NbrJoueurMax { get; set; }
        [Display(Name = "Temps minimal")]
        public int TempsMin { get; set; }
        [Display(Name = "Temps Maximal")]
        public Nullable<int> TempsMax { get; set; }
        [Display(Name = "Date d'ajout")]
        public System.DateTime DateAjout { get; set; }
        [Display(Name = "Type de jeu")]
        public string IdTypesJeu { get; set; }
        public string IdLocationJeu { get; set; }
        public int TypesJeuId_Id { get; set; }
        public Nullable<int> LocationJeuId_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiviteJeu> ActiviteJeus { get; set; }
        public virtual LocationJeu LocationJeu { get; set; }
        public virtual TypesJeu TypesJeu { get; set; }
    }
}
