//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRSM.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jeu
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public int Difficulte { get; set; }
        public int NbrJoueurMin { get; set; }
        public int NbrJoueurMax { get; set; }
        public int TempsMin { get; set; }
        public int TempsMax { get; set; }
        public System.DateTime DateAjout { get; set; }
        public Nullable<int> IdLocationJeu { get; set; }
    
        public virtual LocationJeu LocationJeu { get; set; }
    }
}
