//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRSM.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jeux
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string NbrJoueur { get; set; }
        public string Temps { get; set; }
        public int MembreId { get; set; }
    
        public virtual Membre Membre { get; set; }
    }
}
