//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRSM.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationDocument
    {
        public int Id { get; set; }
        public System.DateTime DateEmprunt { get; set; }
        public System.DateTime DateRetour { get; set; }
        public System.DateTime DateEffective { get; set; }
        public string NoDossier { get; set; }
        public string IdDocument { get; set; }
    
        public virtual Membre membre { get; set; }
        public virtual Document DocumentId { get; set; }
    }
}
