//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRSM.Models.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Membre : IMembre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membre()
        {
            this.PublicationId = new HashSet<Publication>();
            this.LocationDocumentId = new HashSet<LocationDocument>();
            this.LocationJeuId = new HashSet<LocationJeu>();
            this.ParticipantsId = new HashSet<Participants>();
        }
    
        public int Id { get; set; }
        public string NoDossier { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public string Role { get; set; }
        public string MDP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> PublicationId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationDocument> LocationDocumentId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationJeu> LocationJeuId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> ParticipantsId { get; set; }

        public void Modifier(IMembre membre, IUnitOfWork contexte)
        {
            Membre modifier = contexte.Membre.Find(membre.Id);
            modifier.MDP = membre.MDP;
            modifier.Nom = membre.Nom;
            modifier.Prenom = membre.Prenom;
            modifier.Role = membre.Role;
            contexte.Membre.Update(modifier);
            contexte.Membre.Save();
        }

        public void ModifierPremiereConnexion(IMembre membre, IUnitOfWork contexte)
        {
            Membre modifier = contexte.Membre.Find(membre.Id);
            //modifier.Activite = null;
            //modifier.Jeux = null;
            //modifier.Livres = null;
            //modifier.Publication = null;
            modifier.MDP = membre.MDP;
            modifier.Nom = membre.Nom;
            modifier.Prenom = membre.Prenom;
            modifier.Role = membre.Role;
            contexte.Membre.Update(modifier);
            contexte.Membre.Save();
        }

        public IMembre Trouver(string NoDossier, IUnitOfWork contexte)
        {
            return contexte.Membre.Get(m => m.NoDossier.Contains(NoDossier)).First();
        }

        public Document AjouterDocument()
        {
            throw new NotImplementedException();
        }

        public Jeu AjouterJeu()
        {
            throw new NotImplementedException();
        }

        public Publication AjouterPublication()
        {
            throw new NotImplementedException();
        }
    }
}
