//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRSM.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membre : IMembre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membre()
        {
            this.PublicationId = new HashSet<Publication>();
            this.LocationDocumentId = new HashSet<LocationDocument>();
            this.LocationJeuId = new HashSet<LocationJeu>();
            this.ParticipantsId = new HashSet<Participants>();
        }
    
        public int Id { get; set; }
        public string NoDossier { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public string Role { get; set; }
        public string MDP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> PublicationId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationDocument> LocationDocumentId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationJeu> LocationJeuId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> ParticipantsId { get; set; }

        public void Modifier(IMembre membre, IUnitOfWork contexte)
        {
            throw new NotImplementedException();
        }

        public void ModifierPremiereConnexion(IMembre membre, IUnitOfWork contexte)
        {
            throw new NotImplementedException();
        }

        public IMembre Trouver(string NoDossier, IUnitOfWork contexte)
        {
            throw new NotImplementedException();
        }

        public Document AjouterDocument()
        {
            throw new NotImplementedException();
        }

        public Jeu AjouterJeu()
        {
            throw new NotImplementedException();
        }

        public Publication AjouterPublication()
        {
            throw new NotImplementedException();
        }
    }
}
