//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donnees.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Types()
        {
            this.Jeux = new HashSet<Jeux>();
        }
    
        public int Id { get; set; }
<<<<<<< HEAD:CJRSM/Donnees/Models/DAL/Types.cs
        public string Etiquette { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jeux> Jeux { get; set; }
=======
        public string MembreId { get; set; }
        public string Titre { get; set; }
        public string Jeu { get; set; }
        public string Description { get; set; }
        public string NbrMembreMin { get; set; }
        public string NbrMembreMax { get; set; }
        public string Jour { get; set; }
        public string HeureDebut { get; set; }
        public string Hebdomadaire { get; set; }
        public string DateDebut { get; set; }
        public string NbrRepetition { get; set; }
        public string Accepte { get; set; }
        public string Participant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membre> Membre { get; set; }
        public virtual Jeux Jeux { get; set; }
>>>>>>> defb080538b62100585d77ff091871497249917d:CJRSM/Donnees/Models/DAL/Activite.cs
    }
}
